sharedEnvironments: &sharedEnvironments
  SPRING_CLOUD_CONSUL_ENABLED: false
  RARIBLE_CORE_APM_AGENT_ENABLED: false
  SPRING_DATA_MONGODB_DATABASE: test-protocol-currency
  APPLICATION_ENVIRONMENT: "infura-test"

protocol-currency-api:
  environments:
    <<: *sharedEnvironments


protocol-currency-job:
  environments:
    <<: *sharedEnvironments
