global:
  environments: &sharedEnv
    MONGODB_HOSTS: "mongo1.rarible.int.,mongo2.rarible.int.,mongo3.rarible.int."
    MONGODB_DATABASE: "protocol-currency"

protocol-currency-api:
  environments:
    <<: *sharedEnv
  replicas: 2

protocol-currency-job:
  environments:
    <<: *sharedEnv
  replicas: 0
