global:
  environments: &sharedEnv
    APPLICATION_ENVIRONMENT: '{{ include "service.env" $ }}'
    SPRING_CONFIG_IMPORT: "configserver:http://protocol-config-service:8080/"
    SPRING_CLOUD_CONFIG_NAME: "currency-service"

protocol-currency-api:
  image:
    repository: currency-service-api
  replicas: 2
  service:
    enabled: true
  environments:
    <<: *sharedEnv
    SPRING_PROFILES_ACTIVE: 'core,core-{{ include "service.env" $ }},{{ include "service.env" $ }},api'
  resources:
    jvm:
      xmx_megabytes: 512
      max_direct_memory_megabytes: 128
  livenessProbe:
    initialDelaySeconds: 600
  updateConfig:
    order: start-first

protocol-currency-job:
  image:
    repository: currency-service-job
  replicas: 1
  environments:
    <<: *sharedEnv
    SPRING_PROFILES_ACTIVE: 'core,core-{{ include "service.env" $ }},{{ include "service.env" $ }},job'
  resources:
    jvm:
      xmx_megabytes: 512
      max_direct_memory_megabytes: 128
  livenessProbe:
    initialDelaySeconds: 600
