protocol-currency-api:
  image:
    repository: currency-service-api
  replicas: 2
  service:
    enabled: true
  environments:
    APPLICATION_ENVIRONMENT: '{{ include "service.env" $ }}'
    CONSUL_ROOT_PATH: '{{ include "service.env" $ }}/protocol/currency'
    SPRING_PROFILES_ACTIVE: 'consul,{{ include "service.env" $ }}'
  nodeSelector:
    node.labels.rarible.service: true
  resources:
    jvm:
      xmx_megabytes: 512
      max_direct_memory_megabytes: 128
  livenessProbe:
    initialDelaySeconds: 600
  updateConfig:
    order: start-first

protocol-currency-job:
  image:
    repository: currency-service-job
  replicas: 1
  environments:
    APPLICATION_ENVIRONMENT: '{{ include "service.env" $ }}'
    CONSUL_ROOT_PATH: '{{ include "service.env" $ }}/protocol/currency'
    SPRING_PROFILES_ACTIVE: 'consul,{{ include "service.env" $ }}'
  nodeSelector:
    node.labels.rarible.service: true
  resources:
    jvm:
      xmx_megabytes: 512
      max_direct_memory_megabytes: 128
  livenessProbe:
    initialDelaySeconds: 600
