protocol-currency-api:
  image:
    repository: currency-service-api
  replicas: 2
  environments:
    APPLICATION_ENVIRONMENT: '{{ include "service.appEnv" $ }}'
    CONSUL_ROOT_PATH: '{{ include "service.appEnv" $ }}/protocol/currency'
    SPRING_PROFILES_ACTIVE: 'consul,{{ include "service.appEnv" $ }}'
  nodeSelector:
    node.labels.rarible.service: true
  resources:
    jvm:
      xmx_megabytes: 512
      max_direct_memory_megabytes: 128
  livenessProbe:
    initialDelaySeconds: 600s
  updateConfig:
    delay: 20s
    order: start-first
  networks:
    common:
    - '{{ include "service.appEnv" $ }}-backend'
    additional:
    - proxy-staging

protocol-currency-job:
  image:
    repository: currency-service-job
  replicas: 1
  environments:
    APPLICATION_ENVIRONMENT: '{{ include "service.appEnv" $ }}'
    CONSUL_ROOT_PATH: '{{ include "service.appEnv" $ }}/protocol/currency'
    SPRING_PROFILES_ACTIVE: 'consul,{{ include "service.appEnv" $ }}'
  nodeSelector:
    node.labels.rarible.service: true
  resources:
    jvm:
      xmx_megabytes: 512
      max_direct_memory_megabytes: 128
  livenessProbe:
    initialDelaySeconds: 600s
  updateConfig:
    delay: 20s
  networks:
    common:
    - '{{ include "service.appEnv" $ }}-backend'
