common:
  coins:
    dai:
      ETHEREUM: "0x3586d3e6cdae98d5f0eeab737977bc78406da2bd"
    weth:
      ETHEREUM: "0xc6f33b62a94939e52e1b074c4ac1a801b869fdb2"
    flow:
      FLOW: "A.7e60df042a9c0868.FlowToken"
    flowusd:
      FLOW: "A.e223d8a629e49c68.FUSD"
    eurs:
      TEZOS: "KT1LP8Zx12yw3nDCmRBPv3HrWZXH1JCQViWu"
