rarible:
  core:
    nginx-expose:
      server: api-staging.rarible.com
common:
  coins:
    dai:
      ETHEREUM: "0x5592ec0cfb4dbc12d3ab100b257153436a1f0fea"
    weth:
      ETHEREUM: "0xc778417e063141139fce010982780140aa0cd5ab"
    flow:
      FLOW: "A.7e60df042a9c0868.FlowToken"
    flowusd:
      FLOW: "A.e223d8a629e49c68.FUSD"
    stasis-eurs:
      TEZOS: "KT1LP8Zx12yw3nDCmRBPv3HrWZXH1JCQViWu:0"
    matic:
      ETHEREUM: "0x7d1afa7b718fb893db30a3abc0cfc608aacfebb0"
