rarible:
  core:
    nginx-expose:
      server: api-e2e.rarible.com
common:
  coins:
    dai:
      ETHEREUM: "0x3586d3e6cdae98d5f0eeab737977bc78406da2bd"
    weth:
      ETHEREUM: "0xc6f33b62a94939e52e1b074c4ac1a801b869fdb2"
    flow:
      FLOW: "A.7e60df042a9c0868.FlowToken"
    flowusd:
      FLOW: "A.e223d8a629e49c68.FUSD"
    stasis-eurs:
      TEZOS: "KT1Rgf9RNW7gLj7JGn98yyVM34S4St9eudMC:0"
    wtez: # alias, not a real coin
      TEZOS: "KT1RggVJ1mMaLJezpdsJ6YtBfL7sBfcaGD1H"
    youves-uusd:
      TEZOS: "KT191NbZCWnCZvoLEgcPpSEx5yVRk7WnisnN:0"
    eurl:
      TEZOS: "KT1XVLypM2M7kVBGuT4p8wkYigCxbh6CMdia:0"
