rarible:
  core:
    nginx-expose:
      server: api-dev.rarible.com
common:
  coins:
    dai:
      ETHEREUM: "0xad6d458402f60fd3bd25163575031acdce07538d"
    weth:
      ETHEREUM: "0xc778417e063141139fce010982780140aa0cd5ab"
    flow:
      FLOW: "A.7e60df042a9c0868.FlowToken"
    flowusd:
      FLOW: "A.e223d8a629e49c68.FUSD"
    stasis-eurs:
      TEZOS: "KT1LP8Zx12yw3nDCmRBPv3HrWZXH1JCQViWu:0"
    matic:
      ETHEREUM: "0x83e556da6514325ee615ff868cd0d324856fa0cf"
