rarible:
  core:
    nginx-expose:
      server: api-staging.rarible.com
common:
  coins:
    dai:
      ETHEREUM: "0x5592ec0cfb4dbc12d3ab100b257153436a1f0fea"
    weth:
      ETHEREUM: "0xc778417e063141139fce010982780140aa0cd5ab"
      POLYGON: "0xa6fa4fb5f76172d178d61b04b0ecd319c5d1c0aa"
    flow:
      FLOW: "A.7e60df042a9c0868.FlowToken"
    flowusd:
      FLOW: "A.e223d8a629e49c68.FUSD"
    stasis-eurs:
      TEZOS: "KT1Rgf9RNW7gLj7JGn98yyVM34S4St9eudMC:0"
    matic-network:
      ETHEREUM: "0x83e556da6514325ee615ff868cd0d324856fa0cf"
    wtez: # alias, not a real coin
      TEZOS: "KT1RggVJ1mMaLJezpdsJ6YtBfL7sBfcaGD1H"
    youves-uusd:
      TEZOS: "KT191NbZCWnCZvoLEgcPpSEx5yVRk7WnisnN:0"
    eurl:
      TEZOS: "KT1PEBh9oKkQosYuw4tvzigps5p7uqXMgdez:0"
    dogami:
      TEZOS: "KT1Em3cZu3PRnvUyvifgAqYBjzuBv8fEAEud"
    immutable-x:
      IMMUTABLEX: "0x26b81657e09d3a6a18ff1c6d776fd09f4bb9ee80"
    imx-usdc:
      IMMUTABLEX: "0x07865c6e87b9f70255377e024ace6630c1eaa37f"
    ecomi:
      IMMUTABLEX: "0x3409d4ad4d3a86a261b27b913a9ee72f7f5650ad"
    guild-of-guardians:
      IMMUTABLEX: "0x3c9b585b4d29b5e0e6be8eb1ee9607cde09f5a57"
    gods-unchained:
      IMMUTABLEX: "0x4c04c39fb6d2b356ae8b06c47843576e32a1963e"
