rarible:
  core:
    nginx-expose:
      server: api-dev.rarible.com
common:
  coins:
    dai:
      ETHEREUM: "0xad6d458402f60fd3bd25163575031acdce07538d"
    dai-newdev:
      EHTEREUM: "0x3867e897ed8C72900281BF27ac9e8D6c7E3615b6"
      POLYGON: "0x938a97375D6809f7FCd191139E6658D6A5109A48"
    weth:
      ETHEREUM: "0x55eb2809896ab7414706aacdde63e3bbb26e0bc6"
      POLYGON: "0xa6fa4fb5f76172d178d61b04b0ecd319c5d1c0aa"
    flow:
      FLOW: "A.7e60df042a9c0868.FlowToken"
    flowusd:
      FLOW: "A.e223d8a629e49c68.FUSD"
    stasis-eurs:
      TEZOS: "KT1Rgf9RNW7gLj7JGn98yyVM34S4St9eudMC:0"
    matic-network:
      ETHEREUM: "0x83e556da6514325ee615ff868cd0d324856fa0cf"
    wtez: # alias, not a real coin
      TEZOS: "KT1RggVJ1mMaLJezpdsJ6YtBfL7sBfcaGD1H"
    youves-uusd:
      TEZOS: "KT191NbZCWnCZvoLEgcPpSEx5yVRk7WnisnN:0"
    eurl:
      TEZOS: "KT1XVLypM2M7kVBGuT4p8wkYigCxbh6CMdia:0"

  aliases:
    dai-newdev: dai
