application:
  project: protocol

server:
  shutdown: graceful
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://${mongodb.hosts}
      database: ${mongodb.database}
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    default-property-inclusion: non_null
  main:
    banner-mode: log
    web-application-type: reactive

common:
  historySince: '2024-01-01T00:00:00Z'
  apiUrl: https://api.coingecko.com/api/v3
  # format:
  # key is CoinGecko id from /coins/list;
  # value is map of platform name to the coins address on the corresponding platform
  coins:
    ethereum:
      ETHEREUM: "0x0000000000000000000000000000000000000000"
      IMMUTABLEX: "0x0000000000000000000000000000000000000000"
      ARBITRUM: "0x0000000000000000000000000000000000000000"
      ZKSYNC: "0x0000000000000000000000000000000000000000"
      LIGHTLINK: "0x0000000000000000000000000000000000000000"
      ASTARZKEVM: "0x0000000000000000000000000000000000000000"
      RARI: "0x0000000000000000000000000000000000000000"
      BASE: "0x0000000000000000000000000000000000000000"
      KROMA: "0x0000000000000000000000000000000000000000"
      ZKLINK: "0x0000000000000000000000000000000000000000"
    optimism:
      OPTIMISM: "0x0000000000000000000000000000000000000000"
    mantle:
      MANTLE: "0x0000000000000000000000000000000000000000"
    chiliz:
      CHILIZ: "0x0000000000000000000000000000000000000000"
    celo:
      CELO: "0x0000000000000000000000000000000000000000"
    fief:
      FIEF: "0x0000000000000000000000000000000000000000"
    oas:
      OASYS: "0x0000000000000000000000000000000000000000"
      SAAKURU: "0x0000000000000000000000000000000000000000"
    xai:
      XAI: "0x0000000000000000000000000000000000000000"
    rose:
      OASIS: "0x0000000000000000000000000000000000000000"
    mat:
      MATCH: "0x0000000000000000000000000000000000000000"
    palm:
      PALM: "0x0000000000000000000000000000000000000000"
    5vire:
      FIVIRE: "0x0000000000000000000000000000000000000000"
  aliases:
    flowusd: usd
    wtez: tezos
    kolibri-usd: usd
    usdtez: usd
    wrapped-usdc: usd
    youves-uusd: usd
    imx-usdc: usd
    eurl: seur # one of EUR stable coins
    test-usd: usd
    blur-pool: weth
    wmnt: mantle
    wchz: chiliz
    wcelo: celo
    wfief: fief
    woas: oas
    wxai: xai
    wrose: rose
    wpalm: palm
    wmat: mat
    w5vire: w5vire

  abbreviations:
    apecoin: "ape"
    arke: "arke"
    ash: "ash"
    atari: "atri"
    blur: "blur"
    blur-pool: "weth"
    cube: "cube"
    imx-usdc: "usdc"
    dai: "dai"
    decentraland: "mana"
    deflect: "deflct"
    dogami: "doga"
    donkey: "donk"
    dynamite: "dyt"
    ecomi: "omi"
    ethereum: "eth"
    eurl: "eurl"
    firdaos: "fdo"
    flow: "flow"
    flowusd: "fusd"
    gamee: "gmee"
    gods-unchained: "gods"
    guild-of-guardians: "gog"
    hue: "hue"
    immutable-x: "imx"
    kolibri-usd: "kusd"
    lux-expression: "lux"
    mantle: "mnt"
    many: "many"
    matic-network: "matic"
    monavale: "mona"
    optimism: "op"
    plenty-dao: "plenty"
    polyient-games-unity: "pgu"
    prosper: "pros"
    rarible: "rari"
    reflect-finance: "rfi"
    revv: "revv"
    rotten: "rot"
    solana: "sol"
    stasis-eurs: "eurs"
    tezos: "xtz"
    wtez: "wxtz"
    terra-virtua-kolect: "tvk"
    the-sandbox: "sand"
    usd-coin: "usdc"
    usdtez: "usdtz"
    weth: "weth"
    wmatic: "wmatic"
    wmnt: "wmnt"
    wchz: "wchz"
    wrapped-usdc: "xusd"
    youves-uusd: "uusd"
    chiliz: "chz"
    arbitrum: "arb"
    oasys: "oas"
    woas: "woas"
    wxai: "wxai"
    xai: "xai"
    rose: "rose"
    wrose: "wrose"
    match: "mat"
    wmatch: "wmat"
    palm: "palm"
    wpalm: "wpalm"
    5vire: "5vire"
    w5vire: "w5vire"
    lightlink: "ll"
