openapi: 3.0.3
info:
paths:

components:
  schemas:

    CurrencyRate:
      type: object
      required:
        - fromCurrencyId
        - toCurrencyId
        - rate
        - date
      properties:
        fromCurrencyId:
          type: string
        toCurrencyId:
          type: string
        rate:
          $ref: '#/components/schemas/BigDecimal'
        date:
          type: string
          format: date-time

    CurrencyApiError:
      required:
        - code
        - message
        - status
      type: object
      properties:
        status:
          type: integer
          format: int32
        code:
          type: string
          enum:
            - UNKNOWN
            - VALIDATION
            - FIRST_TEMPLATE_OBJECT_NOT_FOUND
            - SECOND_TEMPLATE_OBJECT_NOT_FOUND
        message:
          type: string

    BigDecimal:
      type: string
      example: 717802.342336

    Address:
      type: string
      example: '0x60f80121c31a0d46b5279700f9df786054aa5ee5'
